name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - "!package.json"
      - "!CHANGELOG.md"
    branches:
      - master
    
env:
  NODE_ENV: production 

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v2

      - name: 📦 Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: dreamlink-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: ⚙️ Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true

      - name: 👨🏻‍💻 Install dependencies
        run: yarn install

      - name: 🏗️ Build
        env:
          GOOGLE_TAG_MANAGER_ID: GTM-TNK475T
        run: yarn run generate

      - name: ✨ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
