name: Deploy

on:
  workflow_dispatch:
  push:
    tags: [ v* ]

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v3

      - name: 📦 Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: dreamlink-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: ⚙️ Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: 👨🏻‍💻 Install dependencies
        run: yarn install

      - name: 🏗️ Build
        run: yarn run generate

      - name: 🚀 Deploy
        run: yarn run deploy -n www-dreamlink
        timeout-minutes: 20
        env:
          DEPLOY_WEB3STORAGE_TOKEN: ${{ secrets.DEPLOY_WEB3STORAGE_TOKEN }}
          DEPLOY_CLOUDFLARE_EMAIL: ${{ secrets.DEPLOY_CLOUDFLARE_EMAIL }}
          DEPLOY_CLOUDFLARE_KEY: ${{ secrets.DEPLOY_CLOUDFLARE_KEY }}
          DEPLOY_CLOUDFLARE_ZONE: dreamlink.cloud
          DEPLOY_CLOUDFLARE_RECORD: _dnslink.www

      - name: ✨ Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
